# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteMenuItem',
            fields=[
                ('name', models.CharField(help_text='Select name for this menu item.', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Select cost for this menu item.', max_digits=6)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular Menu Item across whole Catalog.', primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select name for this food.', max_length=100, unique=True)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now, help_text='Select expiry date for this food.')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_items', models.ManyToManyField(help_text='Add menu item to this menu.', to='menu.ConcreteMenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemDecorator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select name for this menu item.', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Select cost for this menu item.', max_digits=6)),
                ('change', models.BooleanField(default=True, help_text='Check for food addition. Uncheck for food removal.')),
                ('foods', models.ManyToManyField(help_text='Select foods for this menu item.', to='menu.Food')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concretemenuitem',
            name='decorators',
            field=models.ManyToManyField(help_text='Associate this decorator with a base MenuItem, or many.', to='menu.MenuItemDecorator'),
        ),
        migrations.AddField(
            model_name='concretemenuitem',
            name='foods',
            field=models.ManyToManyField(help_text='Select foods for this menu item.', to='menu.Food'),
        ),
    ]
