# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select expiry date for this food.'),
        ),
    ]
