# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20171117_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretemenuitem',
            name='foods',
            field=models.ManyToManyField(blank=True, help_text='Select foods for this menu item.', null=True, to='menu.Food'),
        ),
        migrations.AlterField(
            model_name='menuitemdecorator',
            name='foods',
            field=models.ManyToManyField(blank=True, help_text='Select foods for this menu item.', null=True, to='menu.Food'),
        ),
    ]
