# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(help_text='Add meal to this menu.', to='menu.MenuItem'),
        ),
    ]
