# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20171117_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select name for this menu item.', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Select cost for this menu item.', max_digits=6)),
                ('foods', models.ManyToManyField(blank=True, help_text='Select foods for this menu item.', to='menu.Food')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.BaseMenuItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='concretemenuitem',
            name='decorators',
        ),
        migrations.RemoveField(
            model_name='concretemenuitem',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='menuitemdecorator',
            name='change',
        ),
        migrations.RemoveField(
            model_name='menuitemdecorator',
            name='foods',
        ),
        migrations.AddField(
            model_name='menuitemdecorator',
            name='additions',
            field=models.ManyToManyField(blank=True, help_text='Foods to add to menu item.', related_name='_menuitemdecorator_additions_+', to='menu.Food'),
        ),
        migrations.AddField(
            model_name='menuitemdecorator',
            name='subtractions',
            field=models.ManyToManyField(blank=True, help_text='Foods to remove from menu item.', related_name='_menuitemdecorator_subtractions_+', to='menu.Food'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(help_text='Add menu item to this menu.', to='menu.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitemdecorator',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Select cost for this decorator item.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuitemdecorator',
            name='name',
            field=models.CharField(help_text='Select name for this decorator item.', max_length=100),
        ),
        migrations.DeleteModel(
            name='ConcreteMenuItem',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_decorator',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='basemenuitem', chained_model_field='basemenuitem', on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItemDecorator'),
        ),
        migrations.AddField(
            model_name='menuitemdecorator',
            name='head_menu_item',
            field=models.ForeignKey(help_text='Menu Item to decorate.', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.BaseMenuItem'),
        ),
    ]
