# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20171120_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=1, verbose_name='Serves'),
        ),
    ]
