# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 03:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20171119_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_item_decorator',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='base_menu_item', chained_model_field='head_menu_item', on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItemDecorator'),
        ),
    ]
