# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 06:24
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20171119_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemdecorator',
            name='subtractions',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='head_menu_item', chained_model_field='foods', related_name='_menuitemdecorator_subtractions_+', to='menu.Food'),
        ),
    ]
