# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20171119_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemdecorator',
            name='subtractions',
            field=models.ManyToManyField(blank=True, help_text='Foods to remove from menu item.', related_name='_menuitemdecorator_subtractions_+', to='menu.Food'),
        ),
    ]
