# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20171119_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemenuitem',
            name='meal_type',
            field=models.CharField(choices=[('1', 'Appetizer'), ('2', 'Lunch'), ('3', 'Dinner'), ('4', 'Desert'), ('5', 'Breakfast')], max_length=1, null=True),
        ),
    ]
