# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_basemenuitem_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemenuitem',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='menuitemdecorator',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='menuitemdecorator',
            name='head_menu_item',
        ),
        migrations.RemoveField(
            model_name='menuitemdecorator',
            name='subtractions',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='base_menu_item',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_item_decorator',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Select cost for this menu item.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='foods',
            field=models.ManyToManyField(blank=True, help_text='Select foods for this menu item.', to='menu.Food'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('1', 'Appetizer'), ('2', 'Lunch'), ('3', 'Dinner'), ('4', 'Desert'), ('5', 'Breakfast')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Select name for this menu item.', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BaseMenuItem',
        ),
        migrations.DeleteModel(
            name='MenuItemDecorator',
        ),
    ]
