# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20171120_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'verbose_name': 'Ingredient Quantity', 'verbose_name_plural': 'Ingredient Quantities'},
        ),
        migrations.AlterModelOptions(
            name='recipequantity',
            options={'verbose_name': 'Recipe Quantity', 'verbose_name_plural': 'Recipe Quantities'},
        ),
    ]
