# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20171120_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('app', 'Appetizer'), ('lunch', 'Lunch'), ('din', 'Dinner'), ('des', 'Desert'), ('bfast', 'Breakfast')], max_length=100, null=True, verbose_name='Type'),
        ),
    ]
