# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0006_menu_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Private', 'Private'), ('Social', 'Social'), ('Bar', 'Bar')], default='Social', help_text='Event type.', max_length=50)),
                ('numGuests', models.IntegerField(help_text='Enter the number of guests.', verbose_name='Number of Guests')),
                ('date', models.DateField(default=events.models.default_start_day, help_text='Enter date of event.')),
                ('startTime', models.TimeField(default=datetime.time(16, 0), help_text='Specify start time of event.')),
                ('endDate', models.DateField(default=events.models.default_start_day, help_text='If event goes into next day, please edit.')),
                ('endTime', models.TimeField(default=datetime.time(22, 0), help_text='Enter end time.')),
                ('location', models.CharField(help_text='Enter location', max_length=255)),
                ('menu_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('suggested_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('n', 'Notified'), ('w', 'Working On'), ('c', 'Complete')], default='p', help_text='Event Status', max_length=1)),
                ('menu', models.ForeignKey(blank=True, help_text='Choose a menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'permissions': (('can_mark_approved', 'Set event as approved.'),),
            },
        ),
        migrations.CreateModel(
            name='EventInventoryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'verbose_name': 'Event Inventory',
                'verbose_name_plural': 'Event Inventories',
            },
        ),
        migrations.CreateModel(
            name='EventQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount necessary for event.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventInventoryInstance')),
            ],
            options={
                'verbose_name': 'Event Quantity',
                'verbose_name_plural': 'Event Quantities',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Item')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('part_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Item number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountAvailable', models.IntegerField(verbose_name='Amount Available in Inventory')),
                ('amountUnavailable', models.IntegerField(verbose_name='Amount Used from Inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Item')),
            ],
            options={
                'verbose_name': 'Item inventory',
                'verbose_name_plural': 'Item inventories',
            },
        ),
        migrations.AddField(
            model_name='eventquantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Item'),
        ),
        migrations.AddField(
            model_name='eventinventoryinstance',
            name='items',
            field=models.ManyToManyField(through='events.EventQuantity', to='events.Item'),
        ),
    ]
