# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='numGuests',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
