# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinventoryinstance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventinventoryinstance',
            name='items',
        ),
        migrations.RemoveField(
            model_name='eventquantity',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventquantity',
            name='item',
        ),
        migrations.RemoveField(
            model_name='iteminventory',
            name='item',
        ),
        migrations.DeleteModel(
            name='EventInventoryInstance',
        ),
        migrations.DeleteModel(
            name='EventQuantity',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemInventory',
        ),
    ]
