# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171116_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='numGuests',
            field=models.IntegerField(verbose_name='Number of Guests'),
        ),
    ]
