# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171121_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endTime',
        ),
        migrations.AddField(
            model_name='event',
            name='length',
            field=models.DurationField(default=datetime.timedelta(0, 14400)),
        ),
    ]
