# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menu_quantity'),
        ('events', '0004_auto_20171121_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
