# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='length',
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
