# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171121_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Private', 'Private'), ('Social', 'Social'), ('Bar', 'Bar')], default='s', help_text='Event type.', max_length=50),
        ),
    ]
