# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20171122_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='Enter date of event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=datetime.datetime.today, help_text='If event goes into next day, please edit.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Private', 'Private'), ('Social', 'Social'), ('Bar', 'Bar')], default='Social', help_text='Event type.', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='numGuests',
            field=models.IntegerField(help_text='Enter the number of guests.', verbose_name='Number of Guests'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.datetime.now, help_text='Specify start time of event.'),
        ),
    ]
