# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20171122_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Enter end time.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Enter location', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='menu',
            field=models.ForeignKey(blank=True, help_text='Choose a menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
