# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20171122_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('n', 'Notified'), ('w', 'WorkingOn'), ('c', 'Complete')], default='p', help_text='Event Status', max_length=1),
        ),
    ]
