# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20171124_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=events.models.default_start_day, help_text='Enter date of event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=events.models.default_start_day, help_text='If event goes into next day, please edit.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.time(16, 0), help_text='Specify start time of event.'),
        ),
    ]
