# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20171124_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'permissions': (('can_mark_approved', 'Set event as approved.'),)},
        ),
    ]
