# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20171125_0119'),
        ('events', '0012_auto_20171126_2321'),
    ]

    operations = [
    ]
