# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myoccurrence',
            name='event',
        ),
        migrations.DeleteModel(
            name='MyEvent',
        ),
        migrations.DeleteModel(
            name='MyOccurrence',
        ),
    ]
