# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_delete_occurrence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify',
        ),
        migrations.DeleteModel(
            name='ScheduleManager',
        ),
    ]
