# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_notify_occurrance_schedule_schedulemanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occurrance',
            new_name='Occurrence',
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['occurrence__date']},
        ),
    ]
