# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_userprofile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='phone',
        ),
    ]
