# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=50)),
                ('address', models.CharField(help_text='Enter address', max_length=200)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], help_text='Enter an employee role', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='expertise',
            field=models.ManyToManyField(help_text='Assign role to employee', to='employee.Role'),
        ),
    ]
