# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(max_length=30)),
                ('eventID', models.CharField(max_length=100)),
                ('eventPlace', models.CharField(max_length=100)),
                ('eventStartTime', models.TimeField()),
                ('eventDate', models.DateField()),
            ],
        ),
    ]
