# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_auto_20171109_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catering_TotalEvent',
            new_name='TotalEvent',
        ),
    ]
