# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_auto_20171109_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalevent',
            name='Guests',
            field=models.IntegerField(default=10),
        ),
    ]
