# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_auto_20171127_2256'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage_hour', models.DecimalField(decimal_places=2, default=15.3, max_digits=4)),
                ('hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_temp', models.BooleanField(default=False)),
                ('event', models.ManyToManyField(blank=True, help_text='Assign employee to event', to='events.Event')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COOOK', 'COOK'), ('WAITER', 'WAITER'), ('DELIVERY', 'DELIVERY')], help_text='Choose role', max_length=15, null=True, unique=True)),
            ],
        ),
    ]
