# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('COOK', 'COOK'), ('WAITER', 'WAITER'), ('DELIVERY', 'DELIVERY')], help_text='Choose role', max_length=15, null=True, unique=True),
        ),
    ]
