# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 05:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], help_text='Choose an employee role', max_length=50),
        ),
    ]
