# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20171116_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='expertise',
            field=models.ManyToManyField(default='NOROLE', help_text='Assign role to employee', to='management.Role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Enter phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('NOROLE', 'No Role'), ('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], default='NOROLE', help_text='Choose an employee role', max_length=15),
        ),
    ]
