# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_employee_wage_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
