# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20171121_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
