# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20171126_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
    ]
