# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_employee_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
