# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171116_1355'),
        ('management', '0004_auto_20171116_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='event',
            field=models.ForeignKey(help_text='Assign employee to event', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='expertise',
            field=models.ManyToManyField(help_text='Select the employees expertises', to='management.Role'),
        ),
    ]
