# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='expertise',
        ),
        migrations.AddField(
            model_name='employee',
            name='expertise',
            field=models.ForeignKey(help_text='Employee role', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('NOROLE', 'No Role'), ('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], default='NOROLE', help_text='Choose role', max_length=15),
        ),
    ]
