# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20171116_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='expertise',
            new_name='role',
        ),
    ]
