# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20171117_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Assign employee to event', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Employee role', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Role'),
        ),
    ]
