# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20171117_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], help_text='Choose role', max_length=15),
        ),
    ]
