# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20171117_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
