# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(choices=[('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], help_text='Choose role', max_length=15, to='management.Role'),
        ),
    ]
