# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20171117_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], help_text='Choose role', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(blank=True, help_text='Choose role', max_length=15, null=True, to='management.Role'),
        ),
    ]
