# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20171117_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('COOK', 'Cook'), ('WAITER', 'Waiter'), ('DELIVERY', 'Delivery')], help_text='Choose role', max_length=15, null=True),
        ),
    ]
