# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20171117_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_role',
            field=models.ManyToManyField(blank=True, help_text='Choose role', max_length=15, null=True, to='management.Role'),
        ),
    ]
