# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20171117_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assigned_role',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='Choose role', max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Role'),
        ),
    ]
