# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20171117_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assigned_role',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_role',
            field=models.ManyToManyField(to='management.Role'),
        ),
    ]
