# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20171117_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='assigned_role',
            new_name='role',
        ),
    ]
