# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20171118_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('NONE', 'NONE'), ('COOOK', 'COOK'), ('WAITER', 'WAITER'), ('DELIVERY', 'DELIVERY')], default='NONE', help_text='Choose role', max_length=15, unique=True),
        ),
    ]
