# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171116_1355'),
        ('management', '0028_auto_20171118_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='event',
        ),
        migrations.AddField(
            model_name='employee',
            name='event',
            field=models.ManyToManyField(blank=True, help_text='Assign employee to event', null=True, to='events.Event'),
        ),
    ]
