# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20171119_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(blank=True, default=1, to='management.Role'),
        ),
    ]
